SRCS 		= ./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c\
				/./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c\
				/./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c\
				/./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c\
				/./libft/ft_isalnum.c ./libft/ft_isalnum.c ./libft/ft_isalnum.c

OBJS 		= ${SRCS:.c=.o}

RM 			= rm -f

CFLAGS 		= -Wall -Wextra -Werror

OUTPUT		= libft.a

CC 			= gcc

.c.o:
					${CC} -I includes ${CFLAGS} -c $< -o ${<:.c=.o}

all:		${OUTPUT}


${OUTPUT}: 	${OBJS}
					ar rc ${OUTPUT} ${OBJS}

clean:
					${RM} ${OBJS}

fclean:		clean
					${RM} ${OUTPUT}

re:			fclean all

.PHONY: all clean fclean re 
